name: Build and Deploy to GHCR

on:
  push:
    branches: [ main, develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase repository owner
        id: set-repo-owner
        run: echo "REPO_OWNER_LOWERCASE=${{ github.repository_owner.toLowerCase() }}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.set-repo-owner.outputs.REPO_OWNER_LOWERCASE }}/chess-engine-api:latest
            ghcr.io/${{ steps.set-repo-owner.outputs.REPO_OWNER_LOWERCASE }}/chess-engine-api:${{ github.sha }}
